version: '3.7'

services:
  
  internal-gateway:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - Redis__Configuration=redis
      - ReRoutes__0__DownstreamHostAndPorts__0__Host=identity-service
      - ReRoutes__0__DownstreamHostAndPorts__0__Port=80
      - ReRoutes__1__DownstreamHostAndPorts__0__Host=product-service
      - ReRoutes__1__DownstreamHostAndPorts__0__Port=80
      - ReRoutes__2__DownstreamHostAndPorts__0__Host=blogging-service
      - ReRoutes__2__DownstreamHostAndPorts__0__Port=80
      - ReRoutes__3__DownstreamHostAndPorts__0__Host=tenant-management-service
      - ReRoutes__3__DownstreamHostAndPorts__0__Port=80
      - GlobalConfiguration__BaseUrl=http://internal-gateway
    ports:
      - "80"

  backend-admin-app-gateway:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RemoteServices__Default__BaseUrl=http://backend-admin-app-gateway/
      - AuthServer__Authority=http://auth-server:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - Redis__Configuration=redis
      - ReRoutes__0__DownstreamHostAndPorts__0__Host=identity-service
      - ReRoutes__0__DownstreamHostAndPorts__0__Port=80
      - ReRoutes__1__DownstreamHostAndPorts__0__Host=product-service
      - ReRoutes__1__DownstreamHostAndPorts__0__Port=80
      - GlobalConfiguration__BaseUrl=http://backend-admin-app-gateway
    ports:
      - 51531:80

  public-website-gateway:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - Redis__Configuration=redis
      - ReRoutes__0__DownstreamHostAndPorts__0__Host=product-service
      - ReRoutes__0__DownstreamHostAndPorts__0__Port=80
      - ReRoutes__1__DownstreamHostAndPorts__0__Host=blogging-service
      - ReRoutes__1__DownstreamHostAndPorts__0__Port=80
      - GlobalConfiguration__BaseUrl=http://public-website-gateway
    ports:
      - 51532:80

  blogging-service:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - ConnectionStrings__Blogging=mongodb://mongodb/MsDemo_Blogging
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
      - RemoteServices__Default__BaseUrl=http://internal-gateway/
    ports:
      - 51521:80

  identity-service:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
    ports:
      - 51522:80

  product-service:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - ConnectionStrings__ProductManagement=Server=sqlserver;Database=MsDemo_ProductManagement;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
    ports:
      - 51523:80

  tenant-management-service:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false      
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
    ports:
      - 51524:80
  
  auth-server:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:51511
      - ConnectionStrings__Default=Server=sqlserver;Database=MsDemo_Identity;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=yourStrong(!)Password;Integrated Security=false
      - Redis__Configuration=redis
      - RabbitMQ__Connections__Default__HostName=rabbitmq
    ports:
      - 51511:51511

  backend-admin-app:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - RemoteServices__Default__BaseUrl=http://backend-admin-app-gateway/
      - Redis__Configuration=redis
    ports:
      - 51512:80

  public-website:
    environment:
      - ElasticSearch__Url=http://elasticsearch:9200
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - AuthServer__Authority=http://auth-server:51511
      - RemoteServices__Default__BaseUrl=http://public-website-gateway/
      - Redis__Configuration=redis
    ports:
      - 51513:80