version: '3.7'

services:
  sqlserver:

  migrations:
     image: 'hsaas/migrations:${TAG:-latest}'
     build:
       context: .
       dockerfile: databases/Dockerfile
     depends_on:
       - sqlserver

restore-database:
image: 'hsaas/hsaas-restore-database:${TAG:-latest}'
  build:
      context: .
      dockerfile: databases/restore/Dockerfile
    volumes:
      - dbdata:/var/opt/mssql
    environment:
      - SA_PASSWORD=yourStrong(!)Password
    depends_on:
      - sqlserver
